services:
  bsc:
    image: ghcr.io/bnb-chain/bsc:latest
    container_name: efikcoin-bsc
    restart: unless-stopped

    command:
      - geth
      - --config=/bsc/config/config.toml
      - --datadir=/bsc/node
      - --cache=10000
      - --rpc.allow-unprotected-txs
      - --history.transactions=0
      - --history.logs=576000
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=localhost,rpc.efikcoin.com
      - --http.corsdomain=*
      - --http.api=eth,net,web3

    ports:
      # JSON-RPC
      - "127.0.0.1:8545:8545"

      # P2P
      - "30311:30311/tcp"
      - "30311:30311/udp"

    volumes:
      - ./config:/bsc/config:ro
      - ./data/node:/bsc/node

    stop_grace_period: 2m
